# 《实用Python编程》教学代码
## 第4章 基于Pandas的表格数据处理与分析

## 读取表格化文件

In [20]:
df = pd.read_csv("pybook-data/ch3/rawdata.txt",header=None) # 对于不带表头也就是第一行即为数据的文件，需要指定参数head为None
df = pd.read_csv("students.csv", header=None)
df.head()

    0  1           2           3      4     5       6    7    8
0  张伟  男  1999-05-12  2018010101  计算机学院  2018  江苏省南京市  3.6  142
1  李静  女  2000-08-23  2019020203   经济学院  2019  浙江省杭州市  3.8  126
2  王明  男  2001-02-14  2020030305  外国语学院  2020  广东省广州市  3.2  108
3  刘芳  女  1999-11-05  2018040407    法学院  2018  湖北省武汉市  3.7  156
4  陈浩  男  2000-07-19  2019050509    医学院  2019  四川省成都市  3.9  132

In [22]:
df = pd.read_csv("students.csv", header=None, 
                 names="姓名,性别,出生日期,学号,所属学院,入学年份,籍贯,GPA,总学分".split(','))
df.head()

   姓名 性别        出生日期          学号   所属学院  入学年份      籍贯  GPA  总学分
0  张伟  男  1999-05-12  2018010101  计算机学院  2018  江苏省南京市  3.6  142
1  李静  女  2000-08-23  2019020203   经济学院  2019  浙江省杭州市  3.8  126
2  王明  男  2001-02-14  2020030305  外国语学院  2020  广东省广州市  3.2  108
3  刘芳  女  1999-11-05  2018040407    法学院  2018  湖北省武汉市  3.7  156
4  陈浩  男  2000-07-19  2019050509    医学院  2019  四川省成都市  3.9  132

## 示例代码4.18 创建Series对象的不同方式

In [2]:
import pandas as pd
import numpy as np
#使用列表的方式创建Series，内容为2023年人大理科各专业在福建的最高录取分数
scores_list = [671, 685, 676, 686, 672, 672, 672, 678, 679, 674, 680, 672, 671, 653, 642]
s0 = pd.Series(scores_list)
#使用Numpy的方式创建Series，内容同上
scores_numpy = np.array([671, 685, 676, 686, 672, 672, 672, 678, 679, 674, 680, 672, 671, 653, 642])
s1 = pd.Series(scores_numpy)
#使用字典的方式创建Series
scores_dict = {"外国语言文学类":671, "金融学类":685,"经济学类":676,"法学":686,"工商管理类":672,
                "社会科学试验班（大数据技术与农林经管双主学位项目）":672,
                "社会科学试验班（应用经济与农村发展管理双主学位项目）":672,"统计学类":678,
                "人工智能（拔尖班）":679,"计算机类":674,"计算机类（图灵实验班）":680,
                "数学类（英才班）":672,"应用心理学":671,"金融学（中外合作办学）":653,
                "人力资源管理（中外合作办学）":642}
s2 = pd.Series(scores_dict)
#使用索引的方式创建Series
scores_data = [671, 685, 676, 686, 672, 672, 672, 678, 679, 674, 680, 672, 671, 653, 642]
scores_index = ["外国语言文学类", "金融学类","经济学类","法学","工商管理类",
                "社会科学试验班（大数据技术与农林经管双主学位项目）",
                "社会科学试验班（应用经济与农村发展管理双主学位项目）","统计学类",
                "人工智能（拔尖班）","计算机类","计算机类（图灵实验班）",
                "数学类（英才班）","应用心理学","金融学（中外合作办学）",
                "人力资源管理（中外合作办学）"]
s3 = pd.Series(scores_data, index=scores_index)

In [4]:
s0

0     671
1     685
2     676
3     686
4     672
5     672
6     672
7     678
8     679
9     674
10    680
11    672
12    671
13    653
14    642
dtype: int64

In [5]:
s1

0     671
1     685
2     676
3     686
4     672
5     672
6     672
7     678
8     679
9     674
10    680
11    672
12    671
13    653
14    642
dtype: int64

In [6]:
s2

外国语言文学类                       671
金融学类                          685
经济学类                          676
法学                            686
工商管理类                         672
社会科学试验班（大数据技术与农林经管双主学位项目）     672
社会科学试验班（应用经济与农村发展管理双主学位项目）    672
统计学类                          678
人工智能（拔尖班）                     679
计算机类                          674
计算机类（图灵实验班）                   680
数学类（英才班）                      672
应用心理学                         671
金融学（中外合作办学）                   653
人力资源管理（中外合作办学）                642
dtype: int64

In [7]:
s3

外国语言文学类                       671
金融学类                          685
经济学类                          676
法学                            686
工商管理类                         672
社会科学试验班（大数据技术与农林经管双主学位项目）     672
社会科学试验班（应用经济与农村发展管理双主学位项目）    672
统计学类                          678
人工智能（拔尖班）                     679
计算机类                          674
计算机类（图灵实验班）                   680
数学类（英才班）                      672
应用心理学                         671
金融学（中外合作办学）                   653
人力资源管理（中外合作办学）                642
dtype: int64

## 示例代码4.19 读取Serie对象中的数据

In [27]:
print(s2.values)    #查看所有值
print(s2.index)     #查看所有索引
print(s2.iloc[10])       #位置索引，查看法学专业分数
print(s2.iloc[[3, 10]])  #位置索引列表，查看法学和计算机类
print(s2.loc["法学"])    #标签索引，查看指定专业的分数线
print(s2.loc[["法学", "计算机类（图灵实验班）"]]) #标签索引列表，查看多个专业的分数线

[671 685 676 686 672 672 672 678 679 674 680 672 671 653 642]
Index(['外国语言文学类', '金融学类', '经济学类', '法学', '工商管理类', '社会科学试验班（大数据技术与农林经管双主学位项目）',
       '社会科学试验班（应用经济与农村发展管理双主学位项目）', '统计学类', '人工智能（拔尖班）', '计算机类',
       '计算机类（图灵实验班）', '数学类（英才班）', '应用心理学', '金融学（中外合作办学）', '人力资源管理（中外合作办学）'],
      dtype='object')
680
法学             686
计算机类（图灵实验班）    680
dtype: int64
686
法学             686
计算机类（图灵实验班）    680
dtype: int64

In [40]:
s = pd.Series({'外国语言文学类':671,'金融学类':685,'经济学':676})
print(s.index)
print(s.values)
print('-'*20)
print(s.loc['经济学'])
print('-'*20)
print(s.loc[['金融学类','经济学']])

Index(['外国语言文学类', '金融学类', '经济学'], dtype='object')
[671 685 676]
--------------------
676
--------------------
金融学类    685
经济学     676
dtype: int64

## 示例代码4.20 非数值型Series，其values可同时包含不同数据类型

In [41]:
s4 = pd.Series(['E.B.', 'White', 'Male', 'American', 1899, 1985])
s5 = pd.Series(['E.B.', 'White', 'Male', 'American', 1899, 1985], 
              index=["First-Name", "Family-Name", "Gender", "Nationality", "Born", "Died"])

In [42]:
s4

0        E.B.
1       White
2        Male
3    American
4        1899
5        1985
dtype: object

In [43]:
s5

First-Name         E.B.
Family-Name       White
Gender             Male
Nationality    American
Born               1899
Died               1985
dtype: object

## 示例代码4.21 调用Series.describe()进行数据统计

In [46]:
d = s2.describe() 
print(d['count'], d['mean'], d['min'], d['max']) # 输出 15.0 672.2 642.0 686.0
t = pd.Series(['t1', 't1', 't1', 't2', 't3', 't3'])
d = t.describe()
print(d)

15.0 672.2 642.0 686.0
count      6
unique     3
top       t1
freq       3
dtype: object

## 示例代码4.22 Series数据筛选

In [59]:
d = s2.describe()
print(s2[s2>d['mean']])

金融学类           685
经济学类           676
法学             686
统计学类           678
人工智能（拔尖班）      679
计算机类           674
计算机类（图灵实验班）    680
dtype: int64

In [56]:
s2.to_frame(name='投档线')

                            投档线
外国语言文学类                     671
金融学类                        685
经济学类                        676
法学                          686
工商管理类                       672
社会科学试验班（大数据技术与农林经管双主学位项目）   672
社会科学试验班（应用经济与农村发展管理双主学位项目）  672
统计学类                        678
人工智能（拔尖班）                   679
计算机类                        674
计算机类（图灵实验班）                 680
数学类（英才班）                    672
应用心理学                       671
金融学（中外合作办学）                 653
人力资源管理（中外合作办学）              642

In [60]:
s2[s2>d['mean']].to_frame()

               0
金融学类         685
经济学类         676
法学           686
统计学类         678
人工智能（拔尖班）    679
计算机类         674
计算机类（图灵实验班）  680

## 示例代码4.23 创建一个简单的DataFrame对象

In [61]:
dates = pd.date_range("20200901", periods=3)
data = [[12, 20, "晴"], [9, 18, "小雨"], [12, 23, "多云"]]
df = pd.DataFrame(data, index=dates, columns=["low-temp", "high-temp", "weather"])
df

            low-temp  high-temp weather
2020-09-01        12         20       晴
2020-09-02         9         18      小雨
2020-09-03        12         23      多云

## 示例代码4.24 DataFrame中的数据添加与删除

In [62]:
# 添加两条（行）新记录
df.loc["2020-09-04"] = [10, 22, "小雨"]
df.loc["2020-09-05"] = [10, 24, np.nan] # np.nan表示缺失值
# 连续添加记录
for i in range(5):
    df.loc[len(df)] = [11, 25, "阴"]
# 添加一列
df['温差'] = df['high-temp'] - df['low-temp']
# 原地删除存在缺失值的记录（对应2020-09-05索引的行）
df.dropna(inplace=True) 
# 原地删除新增加的列
df.drop(columns=['温差'], inplace=True)
# 原地删除重复记录
df.drop_duplicates(inplace=True)
# 原地删除最后一行
df.drop(df.index[-1], inplace=True)
df

                     low-temp  high-temp weather
2020-09-01 00:00:00      12.0       20.0       晴
2020-09-02 00:00:00       9.0       18.0      小雨
2020-09-03 00:00:00      12.0       23.0      多云
2020-09-04               10.0       22.0      小雨

## 课堂练习4-2-1

小明这一周点了4次外卖。外卖信息如下


| 餐厅 | 消费(单位:元) |
|:--| --:|
|麦当劳 | 35|
|沙县小吃 | 15|
|海底捞火锅 | 120|
|轻食沙拉日记 | 45|

请利用pandas为小明做一个电子账单，算一算这周外卖总共花了多少钱。

## 示例代码4.25 Pandas表格拼接与合并

In [82]:
df1 = pd.DataFrame({'姓名': ['张三', '李四'], '语文': [85, 92]})
df2 = pd.DataFrame({'姓名': ['王五', '赵六'], '语文': [88, 95]})
df3 = pd.DataFrame({'姓名': ['李四', '张三'], '数学': [90, 75]})
df4 = pd.concat([df1, df2], axis=0, ignore_index=True) # 纵向拼接
df5 = pd.concat([df1, df3['数学']], axis=1) # 横向拼接
df6 = pd.merge(df1, df3, on='姓名')

In [79]:
df4

   姓名  语文
0  张三  85
1  李四  92
2  王五  88
3  赵六  95

In [80]:
df5

   姓名  语文  数学
0  张三  85  90
1  李四  92  75

In [81]:
df6

   姓名  语文  数学
0  张三  85  75
1  李四  92  90

## 示例代码4.26 人民大学在北京市各专业最低录取分历年数据汇总

In [85]:
# Step 1. 读取每年的录取分数表
years = [2020, 2021, 2022, 2023]
dfs = {}
for year in years:
    csv_file = f'pybook-data/ruc_data/北京市/{year}.csv'
    dfs[year] = pd.read_csv(csv_file)
    
# Step 2. 按专业合并最低分
columns = ['专业名称', '最低分']
merged_bj = dfs[years[0]][columns].rename(columns={'最低分': years[0]})
for year in years[1:]:
    sub_table = dfs[year][columns].rename(columns={'最低分': year})
    merged_bj = pd.merge(merged_bj, sub_table, on='专业名称')
    
# Step 3. 对各专业按照分数由新到旧、由高到低排序    
merged_bj.sort_values(years[::-1], ascending=[False]*len(years), ignore_index=True, inplace=True)

merged_bj

      专业名称   2020   2021   2022  2023
0       法学  682.0  674.0  678.0   678
1     金融学类  676.0  672.0  679.0   675
2     经济学类  674.0  667.0  674.0   673
3     财政学类  674.0  670.0  676.0   672
4   新闻传播学类  675.0  667.0  674.0   671
5     国际政治  672.0  666.0  670.0   671
6     社会学类  673.0  666.0  670.0   670
7    工商管理类  673.0  668.0  673.0   669
8  外国语言文学类  669.0  657.0  669.0   663

## 示例代码4.27 计算各专业相比当年最低分平均值的偏差

In [89]:
# Step 1. 按列取平均（跳过第1列"专业名称"）
mean_s = merged_bj.iloc[:, 1:].mean() 
# Step 2. 计算偏差 
diff = merged_bj.iloc[:, 1:].subtract(mean_s)
# Step 3. 观察结果
out = pd.concat([merged_bj[['专业名称']], diff.add_suffix('_偏差')], axis=1)
with pd.option_context('display.float_format', '{:.1f}'.format): # 临时设置浮点格式
    print(out)

      专业名称  2020_偏差  2021_偏差  2022_偏差  2023_偏差
0     财政学类     -0.2      2.6      2.3      0.7
1       法学      7.8      6.6      4.3      6.7
2    工商管理类     -1.2      0.6     -0.7     -2.3
3     国际政治     -2.2     -1.4     -3.7     -0.3
4     金融学类      1.8      4.6      5.3      3.7
5     经济学类     -0.2     -0.4      0.3      1.7
6     社会学类     -1.2     -1.4     -3.7     -1.3
7   新闻传播学类      0.8     -0.4      0.3     -0.3
8  外国语言文学类     -5.2    -10.4     -4.7     -8.3

In [90]:
diff

       2020       2021      2022      2023
0 -0.222222   2.555556  2.333333  0.666667
1  7.777778   6.555556  4.333333  6.666667
2 -1.222222   0.555556 -0.666667 -2.333333
3 -2.222222  -1.444444 -3.666667 -0.333333
4  1.777778   4.555556  5.333333  3.666667
5 -0.222222  -0.444444  0.333333  1.666667
6 -1.222222  -1.444444 -3.666667 -1.333333
7  0.777778  -0.444444  0.333333 -0.333333
8 -5.222222 -10.444444 -4.666667 -8.333333

In [91]:
out

      专业名称   2020_偏差    2021_偏差   2022_偏差   2023_偏差
0     财政学类 -0.222222   2.555556  2.333333  0.666667
1       法学  7.777778   6.555556  4.333333  6.666667
2    工商管理类 -1.222222   0.555556 -0.666667 -2.333333
3     国际政治 -2.222222  -1.444444 -3.666667 -0.333333
4     金融学类  1.777778   4.555556  5.333333  3.666667
5     经济学类 -0.222222  -0.444444  0.333333  1.666667
6     社会学类 -1.222222  -1.444444 -3.666667 -1.333333
7   新闻传播学类  0.777778  -0.444444  0.333333 -0.333333
8  外国语言文学类 -5.222222 -10.444444 -4.666667 -8.333333

## 示例代码4.28 利用lambda操作批处理表格数据

In [92]:
rescaled = merged_bj.iloc[:,1:].apply(lambda x:x/750*100) #跳过第1列（专业名称）
rescaled = pd.concat([merged_bj.iloc[:,0], rescaled], axis=1) #拼接第1列与转换后的分数列，形成完整表格
rescaled

      专业名称       2020       2021       2022       2023
0     财政学类  89.866667  89.333333  90.133333  89.600000
1       法学  90.933333  89.866667  90.400000  90.400000
2    工商管理类  89.733333  89.066667  89.733333  89.200000
3     国际政治  89.600000  88.800000  89.333333  89.466667
4     金融学类  90.133333  89.600000  90.533333  90.000000
5     经济学类  89.866667  88.933333  89.866667  89.733333
6     社会学类  89.733333  88.800000  89.333333  89.333333
7   新闻传播学类  90.000000  88.933333  89.866667  89.466667
8  外国语言文学类  89.200000  87.600000  89.200000  88.400000

## 示例代码4.29 人民大学各专业填报热度分析

In [128]:
from pathlib import Path

# Step 1. 获得所有省份2023年的CSV文件列表
root_path = Path('pybook-data/ruc_data')
csv_files = list(root_path.rglob('2023.csv'))
csv_files = [str(x) for x in csv_files]

# Step 2. 读入各省的招生数据表并清洗数据
tables = [None]*len(csv_files)
for i,csv_fname in enumerate(csv_files):
    prov = csv_fname.split('/')[-2]
    df = pd.read_csv(csv_fname).rename(columns={'理工/物理类 最低':'最低分'})  
    sub_table = df[['专业名称','最低分']].drop_duplicates() # 只统计理工类，去掉可能存在的重复记录 
    sub_table.insert(0, '省份', [prov]*len(sub_table))
    tables[i] = sub_table.dropna() # 去掉没有理工类的记录
    
# Step 3. 将各省各专业投档分纵向拼接成一个长表
long_table = pd.concat(tables, ignore_index=True)
print('记录数:', len(long_table)) # 记录数: 537

# Step 4. 透视重组，获得一个宽表，每行代表一个省份，每列对应一个专业
wide_table = long_table.pivot(index='省份', columns='专业名称', values='最低分')

# Step 5. 专业热度统计
#wide_table.fillna(0, inplace=True) #先用0填充缺失值
wide_table['最高分专业'] = wide_table.idxmax(axis=1) #找出每个省（直辖市）投档线最高的专业
wide_table['最高分'] = wide_table.iloc[:, :-1].max(axis=1) #单独列出最热门专业的投档分

wide_table[['最高分专业', '最高分']].head(10)

记录数: 537

专业名称                  最高分专业    最高分
省份
上海市                      法学  609.0
云南省                      法学  689.0
内蒙古自治区                 统计学类  653.0
北京市       数学类（金融学与数学双主学位项目）  683.0
吉林省                    金融学类  657.0
四川省               人工智能（拔尖班）  685.0
天津市      政治学、经济学与哲学（PPE实验班）  695.0
宁夏回族自治区                金融学类  617.0
安徽省              经济学类（国家专项）  673.0
山东省               人工智能（拔尖班）  678.0

In [129]:
wide_table['最高分专业'].value_counts().to_frame() # 统计热门专业的省份频率

                        count
最高分专业
法学                         10
金融学类                        7
人工智能（拔尖班）                   6
数学类（金融学与数学双主学位项目）           2
统计学类                        1
政治学、经济学与哲学（PPE实验班）          1
经济学类（国家专项）                  1
经济学类                        1
社会科学试验班（管理学科类，国家专项，区外）      1

## 示例代码4.30 按地区频度校正之后的专业热度估计

In [157]:
s1 = wide_table['最高分专业'].value_counts()
s2 = (wide_table.iloc[:,:-2]>0).sum()
s1.name = '热度'
s2.name = '地区频度'

overview = pd.concat([s1, s2], axis=1).dropna()
overview['占比'] = overview[s1.name] / overview[s2.name]
overview.sort_values(by='占比', ascending=False)

                          热度  地区频度        占比
社会科学试验班（管理学科类，国家专项，区外）   1.0     1  1.000000
经济学类（国家专项）               1.0     2  0.500000
法学                      10.0    24  0.416667
数学类（金融学与数学双主学位项目）        2.0     6  0.333333
人工智能（拔尖班）                6.0    23  0.260870
金融学类                     7.0    29  0.241379
政治学、经济学与哲学（PPE实验班）       1.0     6  0.166667
经济学类                     1.0    27  0.037037
统计学类                     1.0    28  0.035714

In [158]:
s1.to_frame()

                        热度
最高分专业
法学                      10
金融学类                     7
人工智能（拔尖班）                6
数学类（金融学与数学双主学位项目）        2
统计学类                     1
政治学、经济学与哲学（PPE实验班）       1
经济学类（国家专项）               1
经济学类                     1
社会科学试验班（管理学科类，国家专项，区外）   1

In [159]:
s2.to_frame()

                    地区频度
专业名称
中国共产党历史                3
人力资源管理（中外合作办学）         9
人力资源管理（经管试验班）          9
人力资源管理（经管试验班）（区内）      1
人力资源管理（经管试验班，协作计划）     1
...                  ...
财政学（财政学与数学双主学位项目）      7
金融学类                  29
金融学类（国家专项）             2
金融学（中外合作办学）           23
马克思主义理论                3

[68 rows x 1 columns]

## 示例代码4.31 按占比对专业进行排序

In [96]:
bar = int(len(wide_table)*0.3) # 只考虑在全国30%以上省份投放的专业
overview = overview[ overview['地区频度']>=bar ]
overview.sort_values(by='占比', ascending=False)

             热度  地区频度        占比
法学         10.0    24  0.416667
人工智能（拔尖班）   6.0    23  0.260870
金融学类        7.0    29  0.241379
经济学类        1.0    27  0.037037
统计学类        1.0    28  0.035714

## 课堂练习4-2-2

教学系统导出的某次考试成绩如下。请找出每科最好成绩及对应学生的姓名。

```python
raw_data = {
    "姓名": ["张三", "张三", "李四", "李四", "王五", "王五"],
    "学科": ["语文", "数学", "语文", "数学", "语文", "数学"],
    "成绩": [85, 92, 78, 88, 90, 85]
}
score_table = pd.DataFrame(raw_data)
```

In [171]:
raw_data = {
    "姓名": ["张三", "张三", "李四", "李四", "王五", "王五"],
    "学科": ["语文", "数学", "语文", "数学", "语文", "数学"],
    "成绩": [85, 92, 78, 88, 90, 85]
}
score_table = pd.DataFrame(raw_data)
score_table

   姓名  学科  成绩
0  张三  语文  85
1  张三  数学  92
2  李四  语文  78
3  李四  数学  88
4  王五  语文  90
5  王五  数学  85

In [200]:
# type your code here

## 综合应用：高考志愿填报推荐

### 示例代码4.32 抓取2024年北京高考数据

In [160]:
import os
from p3lib.ch3 import url_to_filename, PageDownloader

data_dir = 'beijing'
crawler = PageDownloader(save_dir=data_dir)
#抓取北京市2024年本科普通批录取投档线
target_url = "https://gaokao.eol.cn/bei_jing/dongtai/202407/t20240720_2625168.shtml"
crawler.process(target_url)
score_file = os.path.join(data_dir, f'{url_to_filename(target_url)}.html')
assert(os.path.exists(score_file)) #检查目标网页是否已保存到指定路径
#抓取2024年北京高考分段表
target_url = "https://gaokao.eol.cn/bei_jing/dongtai/202406/t20240625_2619192.shtml"
crawler.process(target_url)
rank_file = os.path.join(data_dir, f'{url_to_filename(target_url)}.html')
assert(os.path.exists(rank_file))

[Status] 开始抓取 https://gaokao.eol.cn/bei_jing/dongtai/202407/t20240720_2625168.shtml
[Status] 已保存到 beijing/aHR0cHM6Ly9nYW9rYW8uZW9sLmNuL2JlaV9qaW5nL2Rvbmd0YWkvMjAyNDA3L3QyMDI0MDcyMF8yNjI1MTY4LnNodG1s.html
[Status] 页面抓取成功
[Status] 开始抓取 https://gaokao.eol.cn/bei_jing/dongtai/202406/t20240625_2619192.shtml
[Status] 已保存到 beijing/aHR0cHM6Ly9nYW9rYW8uZW9sLmNuL2JlaV9qaW5nL2Rvbmd0YWkvMjAyNDA2L3QyMDI0MDYyNV8yNjE5MTkyLnNodG1s.html
[Status] 页面抓取成功

### 示例代码4.33 投档线数据清洗

In [103]:
score_df = pd.read_html(score_file)[0]
score_df = score_df[1:].reset_index(drop=True) #跳过原表第一行，并重置行索引
score_df.columns = ['院校代码', '院校', '专业组代码', '限制', '投档线'] #列重命名
score_df['投档线'] = score_df['投档线'].astype(int) 
score_df

      院校代码      院校 专业组代码     限制  投档线
0     1021    北京大学     2     不限  700
1     1023    清华大学     2     物理  698
2     1021    北京大学     3  物理＋化学  690
3     1023    清华大学     3  物理＋化学  689
4     1021    北京大学     1     不限  688
...    ...     ...   ...    ...  ...
1253  6518    喀什大学     3  物理＋化学  434
1254  6519  新疆政法学院     2  物理＋化学  434
1255  6521  新疆和田学院     3  物理＋化学  434
1256  6522    昌吉学院     3  物理＋化学  434
1257  6523  新疆理工学院     1  物理＋化学  434

[1258 rows x 5 columns]

### 示例代码4.34 统计本科普通批次各高校专业组数量

In [104]:
univ_df = score_df['院校'].value_counts().to_frame().reset_index()
univ_df.columns = ['院校', '专业组数量']
print(f'普通批次共有{len(univ_df)}家高校、{len(score_df)}个专业组') # 普通批次共有591家高校、1258个专业组
major_group = score_df['限制'].value_counts().to_frame().reset_index() #统计专业填报限制情况
major_group

普通批次共有591家高校、1258个专业组

             限制  count
0         物理＋化学    469
1            不限    421
2            物理    111
3   物理＋化学(中外合办)     82
4            历史     31
5      不限(中外合办)     30
6          思想政治     28
7      物理＋化学＋生物     16
8            化学     15
9      物理(中外合办)     12
10           地理     11
11      思想政治＋历史      9
12           生物      8
13        物理＋生物      7
14   思想政治＋历史＋地理      1
15   思想政治(中外合办)      1
16        不限(女)      1
17        物理＋地理      1
18     物理＋化学(女)      1
19  物理＋生物(中外合办)      1
20        历史＋地理      1
21     历史(中外合办)      1

### 示例代码4.35 分段表清洗并规整

In [105]:
rank_df = pd.read_html(rank_file)[0]
rank_df = rank_df[1:].reset_index(drop=True)
rank_df.columns = ['分数', '人数', '位次']
rank_df.iloc[0,0]= "700" #将第一行的700-750替换为700
hit = rank_df['分数'].str.contains(r'本科线', na=False) #正则匹配，查找含有'本科线'字样的行
cutoff = hit.idxmax() #定位本科线对应的行
rank_df = rank_df[:cutoff+1] # 舍弃该行之后的数据
rank_df['分数'] = rank_df['分数'].str.replace(r'（.*?）', '', regex=True) #清除注释（特招线、本科线）
rank_df = rank_df.astype(int)
rank_df

      分数   人数     位次
0    700  117    117
1    699   15    132
2    698   16    148
3    697   17    165
4    696   18    183
..   ...  ...    ...
262  438  170  44347
263  437  156  44503
264  436  149  44652
265  435  137  44789
266  434  134  44923

[267 rows x 3 columns]

### 示例代码4.36 分数转位次

In [107]:
score_rank = rank_df.set_index('分数')['位次'] # 先构造“分数->位次”的映射表
score_df['位次'] = score_df['投档线'].map(score_rank)
score_df

      院校代码      院校 专业组代码     限制  投档线     位次
0     1021    北京大学     2     不限  700    117
1     1023    清华大学     2     物理  698    148
2     1021    北京大学     3  物理＋化学  690    354
3     1023    清华大学     3  物理＋化学  689    384
4     1021    北京大学     1     不限  688    423
...    ...     ...   ...    ...  ...    ...
1253  6518    喀什大学     3  物理＋化学  434  44923
1254  6519  新疆政法学院     2  物理＋化学  434  44923
1255  6521  新疆和田学院     3  物理＋化学  434  44923
1256  6522    昌吉学院     3  物理＋化学  434  44923
1257  6523  新疆理工学院     1  物理＋化学  434  44923

[1258 rows x 6 columns]

### 示例代码4.37 查找指定位次区间的专业组

In [108]:
n_24, n_25 = 6.72, 7.89 # 2024, 2025年北京高考人数（单位：万）
rank_25 = 16470 # 考生当前位次
query = int(rank_25*n_24/n_25+0.5) # 按人数比值修正位次
error = 0.05                      
low  = int(query * (1 - error))
high = int(query * (1 + error))
hit = score_df[(score_df['位次'] >= low) & (score_df['位次'] <= high)]
print(f'2025年位次: {rank_25}，对应2024年位次: {query}')
print(f'位次在[{low}, {high}]的专业组数：{len(hit)}')
"""输出：
2025年位次: 16470，对应2024年位次: 14028
位次在[13326, 14729]的专业组数：47
"""
sub = hit[hit['限制'].str.contains(r'不限') == True]
print(f'无限制的专业组数：{len(sub)}')
sub = hit[hit['限制'].str.contains(r'物理$') == True] 
print(f'限"物理"的专业组数：{len(sub)}')

2025年位次: 16470，对应2024年位次: 14028
位次在[13326, 14729]的专业组数：47
无限制的专业组数：10
限"物理"的专业组数：7

In [164]:
hit

     院校代码          院校 专业组代码           限制  投档线     位次
399  1035      北京语言大学     2           物理  586  13407
400  2110      大连海事大学     4           物理  586  13407
401  3244      南京审计大学     1     不限(中外合办)  586  13407
402  4418   广东以色列理工学院     1  物理＋化学(中外合办)  586  13407
403  6112        长安大学     2           物理  586  13407
404  1030      北京林业大学     1  物理＋化学(中外合办)  585  13610
405  1035      北京语言大学     4        物理＋化学  585  13610
406  1036      中国传媒大学     2  物理＋化学(中外合办)  585  13610
407  1043  中国地质大学(北京)     3        物理＋化学  585  13610
408  1049      北京工业大学     3        物理＋化学  585  13610
409  1049      北京工业大学     5     物理(中外合办)  585  13610
410  2138      东北财经大学     2           物理  585  13610
411  2146     辽宁中医药大学     1        物理＋化学  585  13610
412  2315      东北农业大学     1           不限  585  13610
413  3213        河海大学     4        物理＋化学  585  13610
414  3234      南京林业大学     1           不限  585  13610
415  5201        贵州大学     2        物理＋化学  585  13610
416  1031     北京中医药大学     2        物理＋化学  584  13797
417  1312      河北工业大学     2        物理＋化学  584  13797
418  1401        山西大学     2        物理＋化学  584  13797
419  3212      中国矿业大学     3           物理  584  13797
420  3334      温州肯恩大学     1     不限(中外合办)  584  13797
421  4214      华中农业大学     2           物理  584  13797
422  5111      西南交通大学     1  物理＋化学(中外合办)  584  13797
423  6114      陕西师范大学     4        物理＋生物  584  13797
424  1016      北京电影学院     6           物理  583  14003
425  1501       内蒙古大学     4           历史  583  14003
426  3212      中国矿业大学     4        物理＋化学  583  14003
427  3214        江南大学     3        物理＋化学  583  14003
428  1016      北京电影学院     5           不限  582  14198
429  1052      首都师范大学     1           不限  582  14198
430  1221      天津师范大学     5      思想政治＋历史  582  14198
431  1501       内蒙古大学     5        物理＋化学  582  14198
432  3242        扬州大学     1           不限  582  14198
433  1010      北京体育大学     4        物理＋化学  581  14402
434  1051      首都医科大学     1           不限  581  14402
435  3131      上海理工大学     3           不限  581  14402
436  3131      上海理工大学     4        物理＋化学  581  14402
437  3212      中国矿业大学     1  物理＋化学(中外合办)  581  14402
438  3712  中国石油大学(华东)     2        物理＋化学  581  14402
439  4118        河南大学     3           地理  581  14402
440  6112        长安大学     3        物理＋化学  581  14402
441  1055    首都经济贸易大学     2           不限  580  14596
442  1215      中国民航大学     3         思想政治  580  14596
443  1220     天津中医药大学     5        物理＋化学  580  14596
444  3131      上海理工大学     2  物理＋化学(中外合办)  580  14596
445  4317      长沙理工大学     1  物理＋化学(中外合办)  580  14596